### PR TITLE
upgrade to 9.1.15.0

### PR DESCRIPTION
**Pull request by gmaliar**

### CODE REVIEW

**Review by nadavshatz — COMMENTED** [review]
No bower needed anymore ?

**Comment by gmaliar** [comment]
@nadavshatz we don't use bower in tailor-api or meduza, a more appropriate thing wouuld be to even remove node.js from this image and create another image for the extra node.js dependencies.

Moreover they would also not be needed inside meduza and once we remove the last remaining server-side rendered pages from tailor-api, node.js could be removed as well.

We would need a javascript runtime still for tailor-admin, tailor-styleguide and sidekiq, but we can use this for example instead, https://github.com/cowboyd/therubyrhino

**Comment by nadavshatz** [comment]
@gmaliar All good points. Thanks for the detailed info!

**Review by nadavshatz — APPROVED** [review]
:shipit:

**Pull request merged**
